Remove BOTTDC2, as not available in Dycore

diff --git a/2_lm_c/run b/2_lm_c/run
--- a/2_lm_c/run
+++ b/2_lm_c/run
@@ -43,8 +43,8 @@ cat > INPUT_ORG << EONL
   idbg_level = 4,
  /END
  &TUNING
-   tkhmin = 0.4,
-   tkmmin = 0.4,
+   tkhmin = $LM_NL_TKHMIN_C,
+   tkmmin = $LM_NL_TKMMIN_C,
    mu_rain = 0.5,
    v0snow = 20.0,
    rlam_mom=0.0,
@@ -60,11 +60,11 @@ cat > INPUT_ORG << EONL
    z0m_dia=0.2,
    crsmin=150.0,
    clc_diag=0.5,
-   q_crit=1.6,
-   qc0=0.0002
-   qi0=5E-6
+   q_crit=$LM_NL_TUR_LEN_C,
+   qc0=$LM_NL_QC0_C,
+   qi0=5E-6,
    uc1 = 0.0626,
-   tur_len = 100.0, !Was 250. New tuning by C. Heim
+   tur_len = $LM_NL_TUR_LEN_C,
  /END
 EONL
 
@@ -73,25 +73,25 @@ cat > INPUT_DYN << EONL
     lcpp_dycore=.TRUE.,
     lspubc=.true.,
     itype_spubc=3,
-    rdheight=13500.0
-    nrdtau=3,
-    rlwidth=50000.0,
+    rdheight=$LM_NL_RDHEIGHT_C,
+    nrdtau=${LM_NL_NRDTAU_C},
+    rlwidth=${LM_NL_RLWIDTH_C},
     ldyn_bbc=.false.,
     itype_bbc_w=114,
     betasw=0.4,
     xkd=0.1,
     epsass=0.15,
     lcond=.true.,
-    l_diff_smag = .TRUE.,
-    l_diff_cold_pools = .False.
+    l_diff_smag = ${LM_NL_L_DIFF_SMAG_C},
+    l_diff_cold_pools = ${LM_NL_LDIFF_COLD_POOLS_C},
     lhordiff=.true.,
       itype_hdiff=2,
-      hd_corr_u_bd=0.75,
-      hd_corr_t_bd=0.75,
-      hd_corr_trcr_bd=0.0,
+      hd_corr_u_bd=${LM_NL_HD_CORR_U_BD_C},
+      hd_corr_t_bd=${LM_NL_HD_CORR_T_BD_C},
+      hd_corr_trcr_bd=${LM_NL_HD_CORR_P_BD_C},
       hd_corr_p_bd=0.75,
       hd_corr_u_in=0.0,
-      hd_corr_t_in=0.0,
+      hd_corr_t_in=${LM_NL_HD_CORR_U_IN_C},
       hd_corr_trcr_in=0.0,
       hd_corr_p_in=0.0,
       hd_dhmax=250.,
@@ -207,7 +207,7 @@ cat >INPUT_IO << EONL
  /END
  &GRIBOUT
   yform_write='ncdf',
-  hcomb=$LM_NL_HSTART,$LM_NL_HSTOP ,1,
+  hcomb=$LM_NL_HSTART,$LM_NL_HSTOP,1,
   yvarml='U','V','W','T','PP',
      'QV','QC', 'QS','QR','QI','QG',
      'VIO3','HMO3',
@@ -346,6 +346,17 @@ date
 sacct -j \$SLURM_JOB_ID --format=User,JobID,Jobname,partition,state,time,start,end,elapsed,MaxRss,MaxVMSize,nnodes,ncpus,nodelist,AveCPUFreq
 
 \rm -f .jobid >&/dev/null
+
+# Retry if failed
+if grep -q CLEANUP job.out; then
+  \rm -f .retry >&/dev/null
+else
+  if [ -f .retry ]; then exit 1; fi
+  touch .retry
+  cd .. 
+  ./run_daint.sh
+fi
+
 
 EOF_job
  
